services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always # Container will always restart no matter what happens with it
    tty: true # allocates pseudo-terminal for the container / keep the container running
    volumes:
      - ./mysql:/var/lib/mysql
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    environment:
      - MYSQL_DATABASE=peopledb
      - MYSQL_ROOT_PASSWORD=people
      - MYSQL_USER=user
      - MYSQL_PASSWORD=people_user
    networks:
      - nodenet
    healthcheck: # Mechanism to guarantee if a container is in a healthy state
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 3

  node:
    build: .
    container_name: node
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume 
    tty: true
    networks:
      - nodenet
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - nodenet
    restart: always

networks:
  nodenet:
    driver: bridge
